// This file is auto-generated by @hey-api/openapi-ts

export const AppErrorResponseSchema = {
    type: 'object',
    required: ['status', 'error'],
    properties: {
        error: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const AppResponseData_UserSchema = {
    type: 'object',
    properties: {
        item: {
            type: 'object',
            required: ['id', 'telegram_id', 'username'],
            properties: {
                first_name: {
                    type: ['string', 'null']
                },
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                last_name: {
                    type: ['string', 'null']
                },
                photo_url: {
                    type: ['string', 'null']
                },
                referer_id: {
                    type: ['string', 'null'],
                    format: 'uuid'
                },
                telegram_id: {
                    type: 'integer',
                    format: 'int64'
                },
                username: {
                    type: 'string'
                }
            }
        },
        items: {
            type: ['array', 'null'],
            items: {
                type: 'object',
                required: ['id', 'telegram_id', 'username'],
                properties: {
                    first_name: {
                        type: ['string', 'null']
                    },
                    id: {
                        type: 'string',
                        format: 'uuid'
                    },
                    last_name: {
                        type: ['string', 'null']
                    },
                    photo_url: {
                        type: ['string', 'null']
                    },
                    referer_id: {
                        type: ['string', 'null'],
                        format: 'uuid'
                    },
                    telegram_id: {
                        type: 'integer',
                        format: 'int64'
                    },
                    username: {
                        type: 'string'
                    }
                }
            }
        }
    }
} as const;

export const AppResponseData_UserWithTokenSchema = {
    type: 'object',
    properties: {
        item: {
            type: 'object',
            required: ['id', 'telegram_id', 'username', 'token'],
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                photo_url: {
                    type: ['string', 'null']
                },
                referer_id: {
                    type: ['string', 'null'],
                    format: 'uuid'
                },
                telegram_id: {
                    type: 'integer',
                    format: 'int64'
                },
                token: {
                    type: 'string'
                },
                username: {
                    type: 'string'
                }
            }
        },
        items: {
            type: ['array', 'null'],
            items: {
                type: 'object',
                required: ['id', 'telegram_id', 'username', 'token'],
                properties: {
                    id: {
                        type: 'string',
                        format: 'uuid'
                    },
                    photo_url: {
                        type: ['string', 'null']
                    },
                    referer_id: {
                        type: ['string', 'null'],
                        format: 'uuid'
                    },
                    telegram_id: {
                        type: 'integer',
                        format: 'int64'
                    },
                    token: {
                        type: 'string'
                    },
                    username: {
                        type: 'string'
                    }
                }
            }
        }
    }
} as const;

export const AppResponseMessageSchema = {
    type: 'object',
    required: ['status', 'message'],
    properties: {
        message: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const AppResponse_UserSchema = {
    type: 'object',
    required: ['status', 'data'],
    properties: {
        data: {
            '$ref': '#/components/schemas/AppResponseData_User'
        },
        message: {
            type: ['string', 'null']
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const AppResponse_UserWithTokenSchema = {
    type: 'object',
    required: ['status', 'data'],
    properties: {
        data: {
            '$ref': '#/components/schemas/AppResponseData_UserWithToken'
        },
        message: {
            type: ['string', 'null']
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const UserSchema = {
    type: 'object',
    required: ['id', 'telegram_id', 'username'],
    properties: {
        first_name: {
            type: ['string', 'null']
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        last_name: {
            type: ['string', 'null']
        },
        photo_url: {
            type: ['string', 'null']
        },
        referer_id: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        telegram_id: {
            type: 'integer',
            format: 'int64'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const UserAuthDTOSchema = {
    type: 'object',
    required: ['username', 'telegram_id', 'photo_url', 'first_name', 'last_name', 'query_id', 'hash', 'auth_date', 'signature'],
    properties: {
        auth_date: {
            type: 'string'
        },
        first_name: {
            type: 'string'
        },
        hash: {
            type: 'string'
        },
        last_name: {
            type: 'string'
        },
        photo_url: {
            type: 'string'
        },
        query_id: {
            type: 'string'
        },
        referer_id: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        signature: {
            type: 'string'
        },
        telegram_id: {
            type: 'integer',
            format: 'int64'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const UserUpdateDTOSchema = {
    type: 'object',
    properties: {
        photo_url: {
            type: ['string', 'null']
        },
        points: {
            type: ['integer', 'null'],
            format: 'int32'
        },
        role: {
            type: ['string', 'null']
        }
    }
} as const;

export const UserWithTokenSchema = {
    type: 'object',
    required: ['id', 'telegram_id', 'username', 'token'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        photo_url: {
            type: ['string', 'null']
        },
        referer_id: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        telegram_id: {
            type: 'integer',
            format: 'int64'
        },
        token: {
            type: 'string'
        },
        username: {
            type: 'string'
        }
    }
} as const;