// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { ListError, ListResponse, AuthData, AuthError, AuthResponse, GetData, GetError, GetResponse, UpdateData, UpdateError, UpdateResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get all users
 */
export const list = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<ListResponse, ListError, ThrowOnError>({
    ...options,
    url: '/api/users'
}); };

/**
 * Try to authenticate a user or create a new user and authenticate if user not exists
 */
export const auth = <ThrowOnError extends boolean = false>(options: Options<AuthData, ThrowOnError>) => { return (options?.client ?? client).post<AuthResponse, AuthError, ThrowOnError>({
    ...options,
    url: '/api/users/auth'
}); };

/**
 * Get a user by id
 */
export const get = <ThrowOnError extends boolean = false>(options: Options<GetData, ThrowOnError>) => { return (options?.client ?? client).get<GetResponse, GetError, ThrowOnError>({
    ...options,
    url: '/api/users/{id}'
}); };

/**
 * Update a user by id
 */
export const update = <ThrowOnError extends boolean = false>(options: Options<UpdateData, ThrowOnError>) => { return (options?.client ?? client).patch<UpdateResponse, UpdateError, ThrowOnError>({
    ...options,
    url: '/api/users/{id}'
}); };