// This file is auto-generated by @hey-api/openapi-ts

export type AppErrorResponse = {
    error: string;
    status: string;
};

export type AppResponseData_User = {
    item?: {
        first_name?: (string) | null;
        id: string;
        last_name?: (string) | null;
        photo_url?: (string) | null;
        referer_id?: (string) | null;
        telegram_id: number;
        username: string;
    };
    items?: Array<{
        first_name?: (string) | null;
        id: string;
        last_name?: (string) | null;
        photo_url?: (string) | null;
        referer_id?: (string) | null;
        telegram_id: number;
        username: string;
    }> | null;
};

export type AppResponseData_UserWithToken = {
    item?: {
        id: string;
        photo_url?: (string) | null;
        referer_id?: (string) | null;
        telegram_id: number;
        token: string;
        username: string;
    };
    items?: Array<{
        id: string;
        photo_url?: (string) | null;
        referer_id?: (string) | null;
        telegram_id: number;
        token: string;
        username: string;
    }> | null;
};

export type AppResponseMessage = {
    message: string;
    status: string;
};

export type AppResponse_User = {
    data: AppResponseData_User;
    message?: (string) | null;
    status: string;
};

export type AppResponse_UserWithToken = {
    data: AppResponseData_UserWithToken;
    message?: (string) | null;
    status: string;
};

export type User = {
    first_name?: (string) | null;
    id: string;
    last_name?: (string) | null;
    photo_url?: (string) | null;
    referer_id?: (string) | null;
    telegram_id: number;
    username: string;
};

export type UserAuthDTO = {
    auth_date: string;
    first_name: string;
    hash: string;
    last_name: string;
    photo_url: string;
    query_id: string;
    referer_id?: (string) | null;
    signature: string;
    telegram_id: number;
    username: string;
};

export type UserUpdateDTO = {
    photo_url?: (string) | null;
    points?: (number) | null;
    role?: (string) | null;
};

export type UserWithToken = {
    id: string;
    photo_url?: (string) | null;
    referer_id?: (string) | null;
    telegram_id: number;
    token: string;
    username: string;
};

export type ListResponse = (AppResponse_User);

export type ListError = (AppErrorResponse);

export type AuthData = {
    /**
     * Tg user data
     */
    body: UserAuthDTO;
};

export type AuthResponse = (AppResponse_UserWithToken);

export type AuthError = (AppErrorResponse);

export type GetData = {
    path: {
        /**
         * Record Uuid
         */
        id: string;
    };
};

export type GetResponse = (AppResponse_User);

export type GetError = (AppErrorResponse);

export type UpdateData = {
    /**
     * Update user
     */
    body: UserUpdateDTO;
    path: {
        /**
         * Record Uuid
         */
        id: string;
    };
};

export type UpdateResponse = (AppResponseMessage);

export type UpdateError = (AppErrorResponse);