[package]
name = "minty-backand"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
solana-program = "2.2.1"
borsh = "1.5.7"

[lib]
crate-type = ["cdylib", "lib"]
