// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { CreateSuppliedTokenHandlerData, CreateSuppliedTokenHandlerError, CreateSuppliedTokenHandlerResponse, GetSuppliedTokenListHandlerData, GetSuppliedTokenListHandlerError, GetSuppliedTokenListHandlerResponse } from './types.gen';

export const client = createClient(createConfig());

export const createSuppliedTokenHandler = <ThrowOnError extends boolean = false>(options: Options<CreateSuppliedTokenHandlerData, ThrowOnError>) => { return (options?.client ?? client).post<CreateSuppliedTokenHandlerResponse, CreateSuppliedTokenHandlerError, ThrowOnError>({
    ...options,
    url: '/api/supplied_token/create_supplied_token'
}); };

export const getSuppliedTokenListHandler = <ThrowOnError extends boolean = false>(options?: Options<GetSuppliedTokenListHandlerData, ThrowOnError>) => { return (options?.client ?? client).get<GetSuppliedTokenListHandlerResponse, GetSuppliedTokenListHandlerError, ThrowOnError>({
    ...options,
    url: '/api/supplied_token/get_supplied_token_list'
}); };