// This file is auto-generated by @hey-api/openapi-ts

export type CreateSuppliedTokenBody = {
    market_address: string;
    mint_address: string;
    name: string;
    symbol: string;
    token_pair: string;
};

export type CreateSuppliedTokenResponce = {
    id: string;
};

export type GetSuppliedListParams = {
    page?: (number) | null;
    page_size?: (number) | null;
    period?: (string) | null;
    search_value?: (string) | null;
    sort_by?: (null | SortByVariants);
};

export type GetSupplietListResponse = {
    current_price: number;
    history: Array<(number)>;
    id: string;
    image_url: string;
    name: string;
    price_spread: number;
    symbol: string;
};

export type MarketPairToPriceUpdate = {
    id: string;
    marketpair_id: string;
    new_price: number;
};

export type SortByVariants = 'Trending' | 'Top' | 'Favorites';

export type TestResponse = {
    id: string;
    name: string;
};

export type CreateSuppliedTokenHandlerData = {
    body: CreateSuppliedTokenBody;
};

export type CreateSuppliedTokenHandlerResponse = (CreateSuppliedTokenBody);

export type CreateSuppliedTokenHandlerError = (unknown);

export type GetSuppliedTokenListHandlerData = {
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        page_size?: number;
        /**
         * Period
         */
        period?: string;
        /**
         * Search value
         */
        search_value?: string;
        /**
         * Period
         */
        sort_by?: SortByVariants;
    };
};

export type GetSuppliedTokenListHandlerResponse = (Array<GetSupplietListResponse>);

export type GetSuppliedTokenListHandlerError = unknown;