[package]
name = "tg_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
teloxide = {version = "0.15.0", features = ["macros"]}
tokio = { version =  "1.44.2", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.41"
